In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from utils.OutlierUtils import sanitize_response_name
from utils.FinalUtils import load_ec_csv, create_voltage_schedule

In [2]:
icp_data = 'disln_072325_PtIrTa'
ec_data = '072325_disl_1mVs_5 cycles'

In [3]:
icp_data_path = f'../data/ICP-MS/{icp_data}.csv'
icp_df = pd.read_csv(icp_data_path)
icp_df.set_index('Time', inplace=True)
icp_df

,Replicate,Reading,CV time,Ta -/181(Pulse/CPS),Ir -/193(Pulse/CPS),Pt -/195(Pulse/CPS)
Time,,,,,,
4000.003,1,8878,0.003,0.000000,0.000000,40.000056
4000.453,1,8879,0.453,6.666668,13.333340,26.666692
4000.904,1,8880,0.904,0.000000,6.666668,46.666743
4001.355,1,8881,1.355,0.000000,0.000000,20.000014
4001.805,1,8882,1.805,6.666668,6.666668,53.333433
...,...,...,...,...,...,...
8108.601,1,17996,4108.601,0.000000,0.000000,6.666668
8109.052,1,17997,4109.052,0.000000,0.000000,40.000056
8109.502,1,17998,4109.502,0.000000,0.000000,6.666668
8109.953,1,17999,4109.953,0.000000,0.000000,13.333340
8110.403,1,18000,4110.403,0.000000,0.000000,20.000014

In [4]:
ec_data_path = f'../data/EChem/{ec_data}.txt'
ec_df = load_ec_csv(ec_data_path)
ec_t = ec_df.index
ec_df.columns

ec_df

ParserError: Error tokenizing data. C error: Expected 2 fields in line 63, saw 3

In [ ]:
from utils.FinalUtils import load_trunc_icp_csv
# load_trunc_icp_csv(icp_df: pd.DataFrame, del_start: int, response_delay: int, t: str) -> pd.DataFrame
icp_df = load_trunc_icp_csv(icp_df, del_start=0, response_delay=0)
icp_df

[load_trunc_icp_csv] Starting with shape (9123, 6), del_start=0, response_delay=0
[load_trunc_icp_csv] Original time range: 4000.003 to 8110.403 (range: 4110.4)
[load_trunc_icp_csv] Normalized time range: 0.0 to 4110.4

,Replicate,Reading,CV time,Ta -/181(Pulse/CPS),Ir -/193(Pulse/CPS),Pt -/195(Pulse/CPS)
Time,,,,,,
0.000,1,8878,0.003,0.000000,0.000000,40.000056
0.450,1,8879,0.453,6.666668,13.333340,26.666692
0.901,1,8880,0.904,0.000000,6.666668,46.666743
1.352,1,8881,1.355,0.000000,0.000000,20.000014
1.802,1,8882,1.805,6.666668,6.666668,53.333433
...,...,...,...,...,...,...
4108.598,1,17996,4108.601,0.000000,0.000000,6.666668
4109.049,1,17997,4109.052,0.000000,0.000000,40.000056
4109.499,1,17998,4109.502,0.000000,0.000000,6.666668
4109.950,1,17999,4109.953,0.000000,0.000000,13.333340
4110.400,1,18000,4110.403,0.000000,0.000000,20.000014

# Specify the response index here
## 1 is the first response column, 2 is the second, etc.

In [ ]:
response_index = 1

In [ ]:
# set the response data
if not icp_df.columns.empty:
    cols_to_drop = []
    if 'Time' in icp_df.columns:
        cols_to_drop.append('Time')
    if 'Replicate' in icp_df.columns:
        cols_to_drop.append('Replicate')
    if 'Reading' in icp_df.columns:
        cols_to_drop.append('Reading')

    responses = icp_df.drop(columns=cols_to_drop)
    if responses.empty and not icp_df.empty: # Check if all columns were dropped, and df wasn't empty initially
        raise ValueError("All columns were identified as non-response columns. No response data left.")
else:
    raise ValueError("DataFrame has no columns.")

response = responses.columns[response_index-1]
response_data = icp_df[response]

In [ ]:
from utils.FinalUtils import interpolate
interp_df = interpolate(icp_trunc_df=icp_df, ec_df=ec_df)
interp_df

[interpolate] Starting with ec_df shape: (3511, 2), icp_trunc_df shape: (9123, 6)
[interpolate] ERROR: could not convert string to float: '1.336e+'
Traceback (most recent call last):
  File "c:\Users\ka056854\Box\Bhagawat_Summer_Student\code_development\Final\Tools\utils\FinalUtils.py", line 187, in interpolate
  File "c:\Users\ka056854\AppData\Local\anaconda3\Lib\site-packages\pandas\core\base.py", line 662, in to_numpy
    result = np.asarray(values, dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '1.336e+'

,Replicate,Reading,CV time,Ta -/181(Pulse/CPS),Ir -/193(Pulse/CPS),Pt -/195(Pulse/CPS)
Time,,,,,,
0.000,1,8878,0.003,0.000000,0.000000,40.000056
0.450,1,8879,0.453,6.666668,13.333340,26.666692
0.901,1,8880,0.904,0.000000,6.666668,46.666743
1.352,1,8881,1.355,0.000000,0.000000,20.000014
1.802,1,8882,1.805,6.666668,6.666668,53.333433
...,...,...,...,...,...,...
4108.598,1,17996,4108.601,0.000000,0.000000,6.666668
4109.049,1,17997,4109.052,0.000000,0.000000,40.000056
4109.499,1,17998,4109.502,0.000000,0.000000,6.666668
4109.950,1,17999,4109.953,0.000000,0.000000,13.333340
4110.400,1,18000,4110.403,0.000000,0.000000,20.000014

In [ ]:
from utils.FinalUtils import add_potential_to_dataframe

# I0 minimum starting time
# cycles how often to sample
# T is period

T = 3624 # in seconds

# v is list of voltages to cycler through
v = [0.4, 0.95]  # volts
cycles = 4


tN = create_voltage_schedule(interp_df.copy().index.min(), period=T, voltages=v, cycles=cycles)
tN_df = pd.DataFrame([
    {"time": t, "voltage": v} for t, v in tN.items()
])

tN

{0.0: 0.4,
 3624.0: 0.95,
 7248.0: 0.4,
 10872.0: 0.95,
 14496.0: 0.4,
 18120.0: 0.95,
 21744.0: 0.4,
 25368.0: 0.95}

In [ ]:
applied_voltage_df = add_potential_to_dataframe(tN, interp_df.copy())
applied_voltage_df

INFO: Input shape: (9123, 6), schedule length: 8
INFO: Output shape: (9123, 7)

,Replicate,Reading,CV time,Ta -/181(Pulse/CPS),Ir -/193(Pulse/CPS),Pt -/195(Pulse/CPS),Applied_Voltage (V)
Time,,,,,,,
0.000,1,8878,0.003,0.000000,0.000000,40.000056,0.40
0.450,1,8879,0.453,6.666668,13.333340,26.666692,0.40
0.901,1,8880,0.904,0.000000,6.666668,46.666743,0.40
1.352,1,8881,1.355,0.000000,0.000000,20.000014,0.40
1.802,1,8882,1.805,6.666668,6.666668,53.333433,0.40
...,...,...,...,...,...,...,...
4108.598,1,17996,4108.601,0.000000,0.000000,6.666668,0.95
4109.049,1,17997,4109.052,0.000000,0.000000,40.000056,0.95
4109.499,1,17998,4109.502,0.000000,0.000000,6.666668,0.95
4109.950,1,17999,4109.953,0.000000,0.000000,13.333340,0.95
4110.400,1,18000,4110.403,0.000000,0.000000,20.000014,0.95

# SPECIFY C and M from Regression Equation
# SPECIFY FLOW_RATE

In [ ]:
c = 0
m = 103054
FLOW_RATE = 0.403
AMOUNT_OF_ELEMENT = 1.176

In [ ]:
from utils.DetectionTools import sanitize_response_name

clean_response = sanitize_response_name(response)

final_df = applied_voltage_df.copy()
final_df['Corrected_Time'] = (interp_df.index - (25 + 2730))

final_df[f'{clean_response}-ppb'] = (final_df[response] - c)/m
final_df[f'{clean_response}-ug/hr'] = final_df[f'{clean_response}-ppb'] * 0.001 * 60 * FLOW_RATE
final_df[f'{clean_response}-ug/hr/(ug-[{clean_response}])'] = final_df[f'{clean_response}-ug/hr'] / AMOUNT_OF_ELEMENT

# final_df.set_index('Time', inplace=True)
final_df.to_csv(r'../output/ICPMS-EChem-Combined.csv')
final_df

,Replicate,Reading,CV time,Ta -/181(Pulse/CPS),Ir -/193(Pulse/CPS),Pt -/195(Pulse/CPS),Applied_Voltage (V),Corrected_Time,CV_time-ppb,CV_time-ug/hr,CV_time-ug/hr/(ug-[CV_time])
Time,,,,,,,,,,,
0.000,1,8878,0.003,0.000000,0.000000,40.000056,0.40,-2755.000,2.911095e-08,7.039028e-10,5.985568e-10
0.450,1,8879,0.453,6.666668,13.333340,26.666692,0.40,-2754.550,4.395754e-06,1.062893e-07,9.038208e-08
0.901,1,8880,0.904,0.000000,6.666668,46.666743,0.40,-2754.099,8.772100e-06,2.121094e-07,1.803651e-07
1.352,1,8881,1.355,0.000000,0.000000,20.000014,0.40,-2753.648,1.314845e-05,3.179294e-07,2.703482e-07
1.802,1,8882,1.805,6.666668,6.666668,53.333433,0.40,-2753.198,1.751509e-05,4.235149e-07,3.601317e-07
...,...,...,...,...,...,...,...,...,...,...,...
4108.598,1,17996,4108.601,0.000000,0.000000,6.666668,0.95,1353.598,3.986843e-02,9.640186e-04,8.197437e-04
4109.049,1,17997,4109.052,0.000000,0.000000,40.000056,0.95,1354.049,3.987280e-02,9.641244e-04,8.198337e-04
4109.499,1,17998,4109.502,0.000000,0.000000,6.666668,0.95,1354.499,3.987717e-02,9.642300e-04,8.199235e-04
4109.950,1,17999,4109.953,0.000000,0.000000,13.333340,0.95,1354.950,3.988155e-02,9.643358e-04,8.200135e-04
4110.400,1,18000,4110.403,0.000000,0.000000,20.000014,0.95,1355.400,3.988591e-02,9.644414e-04,8.201032e-04