In [14]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from Tools.utils.OutlierUtils import sanitize_response_name
from utils.FinalUtils import load_ec_csv, create_voltage_schedule

In [15]:
icp_df = pd.read_csv(r'../data/ICP-MS/Example_processed_data_020525_before_25000.csv')
icp_df.set_index('Time', inplace=True)
icp_df

           Pt -/195(Pulse/CPS)
Time
0.000               830.024112
0.150               770.020752
0.301               930.030273
0.451               710.017644
0.601               710.017644
...                        ...
24999.520           160.000896
24999.670            50.000087
24999.821           140.000686
24999.971            80.000224
25000.121           180.001134

[166140 rows x 1 columns]

In [16]:
ec_df = load_ec_csv(r'../data/EChem/Raw data_potential sqwave 0.4-0.95v_1h.csv')
ec_t = ec_df.index
ec_df

          Voltage (V)  Current (A/cm2)
Time (s)
0.00          0.12947    -3.637200e-05
0.02          0.67922     2.874500e-06
0.07          0.67922     7.780200e-06
0.12          0.67922     1.648000e-06
0.14          0.67922     2.261200e-06
...               ...              ...
21739.44      0.67922    -8.048600e-07
21740.36      0.67922    -1.418100e-06
21740.84      0.67922    -1.418100e-06
21741.72      0.67922    -1.916300e-07
21742.72      0.67922    -1.916300e-07

[97127 rows x 2 columns]

In [17]:
from utils.FinalUtils import load_trunc_icp_csv
# load_trunc_icp_csv(icp_df: pd.DataFrame, del_start: int, response_delay: int, t: str) -> pd.DataFrame
icp_df = load_trunc_icp_csv(icp_df, del_start=0, response_delay=0)
icp_df

[load_trunc_icp_csv] Starting with shape (166140, 1), del_start=0, response_delay=0
[load_trunc_icp_csv] Original time range: 0.0 to 25000.121 (range: 25000.121)
[load_trunc_icp_csv] Normalized time range: 0.0 to 25000.121

           Pt -/195(Pulse/CPS)
Time
0.000               830.024112
0.150               770.020752
0.301               930.030273
0.451               710.017644
0.601               710.017644
...                        ...
24999.520           160.000896
24999.670            50.000087
24999.821           140.000686
24999.971            80.000224
25000.121           180.001134

[166140 rows x 1 columns]

# Specify the response index here
## 1 is the first response column, 2 is the second, etc.

In [18]:
response_index = 1

In [19]:
# set the response data
if not icp_df.columns.empty:
    cols_to_drop = []
    if 'Time' in icp_df.columns:
        cols_to_drop.append('Time')
    if 'Replicate' in icp_df.columns:
        cols_to_drop.append('Replicate')
    if 'Reading' in icp_df.columns:
        cols_to_drop.append('Reading')

    responses = icp_df.drop(columns=cols_to_drop)
    if responses.empty and not icp_df.empty: # Check if all columns were dropped, and df wasn't empty initially
        raise ValueError("All columns were identified as non-response columns. No response data left.")
else:
    raise ValueError("DataFrame has no columns.")

response = responses.columns[response_index-1]
response_data = icp_df[response]

In [20]:
from utils.FinalUtils import interpolate
interp_df = interpolate(icp_trunc_df=icp_df, ec_df=ec_df)
interp_df

[interpolate] Starting with ec_df shape: (97127, 2), icp_trunc_df shape: (166140, 1)
[interpolate] Extracted arrays: ec_times (len=97127), ec_potentials (len=97127)
[interpolate] Extracted icp_times (len=166140)
[interpolate] Performing interpolation...
[interpolate] Interpolation completed
[interpolate] Returning dataframe with shape (166140, 3)

           Pt -/195(Pulse/CPS)  Interp_Voltage (V)  Interp_Current (A/cm2)
Time
0.000               830.024112            0.129470           -3.637200e-05
0.150               770.020752            0.679232            2.629140e-06
0.301               930.030273            0.464790           -1.498866e-05
0.451               710.017644            0.679258            3.732990e-06
0.601               710.017644            0.679220            2.157017e-06
...                        ...                 ...                     ...
24999.520           160.000896            0.679220           -1.916300e-07
24999.670            50.000087            0.679220           -1.916300e-07
24999.821           140.000686            0.679220           -1.916300e-07
24999.971            80.000224            0.679220           -1.916300e-07
25000.121           180.001134            0.679220           -1.916300e-07

[166140 rows x 3 columns]

In [21]:
from utils.FinalUtils import add_potential_to_dataframe

# I0 minimum starting time
# cycles how often to sample
# T is period

T = 3624 # in seconds

# v is list of voltages to cycler through
v = [0.4, 0.95]  # volts
cycles = 4


tN = create_voltage_schedule(interp_df.copy().index.min(), period=T, voltages=v, cycles=cycles)
tN_df = pd.DataFrame([
    {"time": t, "voltage": v} for t, v in tN.items()
])

tN

{0.0: 0.4,
 3624.0: 0.95,
 7248.0: 0.4,
 10872.0: 0.95,
 14496.0: 0.4,
 18120.0: 0.95,
 21744.0: 0.4,
 25368.0: 0.95}

In [22]:
applied_voltage_df = add_potential_to_dataframe(tN, interp_df.copy())
applied_voltage_df

INFO: Input shape: (166140, 3), schedule length: 8
INFO: Output shape: (166140, 4)

,Pt -/195(Pulse/CPS),Interp_Voltage (V),Interp_Current (A/cm2),Applied_Voltage (V)
Time,,,,
0.000,830.024112,0.129470,-3.637200e-05,0.4
0.150,770.020752,0.679232,2.629140e-06,0.4
0.301,930.030273,0.464790,-1.498866e-05,0.4
0.451,710.017644,0.679258,3.732990e-06,0.4
0.601,710.017644,0.679220,2.157017e-06,0.4
...,...,...,...,...
24999.520,160.000896,0.679220,-1.916300e-07,0.4
24999.670,50.000087,0.679220,-1.916300e-07,0.4
24999.821,140.000686,0.679220,-1.916300e-07,0.4
24999.971,80.000224,0.679220,-1.916300e-07,0.4
25000.121,180.001134,0.679220,-1.916300e-07,0.4

# SPECIFY C and M from Regression Equation
# SPECIFY FLOW_RATE

In [23]:
c = 0
m = 103054
FLOW_RATE = 0.403
AMOUNT_OF_ELEMENT = 1.176

In [34]:
from utils.DetectionTools import sanitize_response_name

clean_response = sanitize_response_name(response)

final_df = applied_voltage_df.copy()
final_df['Corrected_Time'] = (interp_df.index - (25 + 2730))

final_df[f'{clean_response}-ppb'] = (final_df[response] - c)/m
final_df[f'{clean_response}-ug/hr'] = final_df[f'{clean_response}-ppb'] * 0.001 * 60 * FLOW_RATE
final_df[f'{clean_response}-ug/hr/(ug-[{clean_response}])'] = final_df[f'{clean_response}-ug/hr'] / AMOUNT_OF_ELEMENT

# final_df.set_index('Time', inplace=True)
final_df.to_csv(r'../output/ICPMS-EChem-Combined.csv')
final_df

,Pt -/195(Pulse/CPS),Interp_Voltage (V),Interp_Current (A/cm2),Applied_Voltage (V),Corrected_Time,Pt_-_195(Pulse_CPS)-ppb,Pt_-_195(Pulse_CPS)-ug/hr,Pt_-_195(Pulse_CPS)-ug/hr/(ug-[Pt_-_195(Pulse_CPS)])
Time,,,,,,,,
0.000,830.024112,0.129470,-3.637200e-05,0.4,45.916667,0.008054,0.000195,0.000166
0.150,770.020752,0.679232,2.629140e-06,0.4,45.914167,0.007472,0.000181,0.000154
0.301,930.030273,0.464790,-1.498866e-05,0.4,45.911650,0.009025,0.000218,0.000186
0.451,710.017644,0.679258,3.732990e-06,0.4,45.909150,0.006890,0.000167,0.000142
0.601,710.017644,0.679220,2.157017e-06,0.4,45.906650,0.006890,0.000167,0.000142
...,...,...,...,...,...,...,...,...
24999.520,160.000896,0.679220,-1.916300e-07,0.4,370.742000,0.001553,0.000038,0.000032
24999.670,50.000087,0.679220,-1.916300e-07,0.4,370.744500,0.000485,0.000012,0.000010
24999.821,140.000686,0.679220,-1.916300e-07,0.4,370.747017,0.001359,0.000033,0.000028
24999.971,80.000224,0.679220,-1.916300e-07,0.4,370.749517,0.000776,0.000019,0.000016
25000.121,180.001134,0.679220,-1.916300e-07,0.4,370.752017,0.001747,0.000042,0.000036